# Generated by Django 4.1.1 on 2022-09-21 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chowkidar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='refreshtoken',
            table='chowkidar_refresh_token',
        ),
    ]
